### ISSUE TITLE
Adicionar CODEOWNERS

### ISSUE THREAD

**Issue by biancarosa** [pyladies-brazil/coc#3]
Galera, o que vocês acham de adicionarmos CODEOWNES nesse repositório?

Assim, temos um subset de pessoas responsáveis por revisar o CoC e se alguém mais quiser entrar nessa lista, basta se adicionar como CODEOWNER.

Texto sobre como o arquivo de CODEOWNERS funciona: https://tech.people-doc.com/using-github-codeowners-file.html

**Comment by jtemporal** [comment]
totalmente apoiado! aproveita e me coloca! vou criar um similar no repo do site do tbm :)

**Comment by biancarosa** [comment]
Vou adicionar esse arquivo até a proxima sexta-feira com as pessoas que se manifestarem. Depois disso, quem quiser, manda um PR. Também vou enviar na lista de emails.
